---
title: "Validating PLOS paper analysis"
output:
  html_notebook: default
  html_document: default
---

Here, we validate the concept of predicting movie box office revenue, using pre-release Wikipedia activity data (page views, edits, etc), per:

    Early Prediction of Movie Box Office Success Based on Wikipedia Activity Big Data
    Márton Mestyán, Taha Yasseri , János Kertész
    Published: August 21, 2013http://dx.doi.org/10.1371/journal.pone.0071226


```{r, results="hide"}
library(tidyverse)
library(magrittr)
```

```{r, results="hide"}
read_tsv_append_column <- function(filename){
    ## append id from filename
    df <- read_tsv(filename)
    df$id <- strsplit(filename, "/")[[1]] %>% tail(1) %>% as.integer
    df
}
    
fix_names <- . %>% gsub(" ", "_", .) %>%
    gsub("\\(", "", .) %>%
    gsub("\\)", "", .) %>%
    tolower
```

```{r, results="hide"}
sample_of_312 <- read_tsv("../data/wikipredict_data_pack/sample_of_312/sample_of_312")
names(sample_of_312) %<>% fix_names

predictors_files <- list.files(path="../data/wikipredict_data_pack/sample_of_312/wikipedia_predictors",
                               full.names=TRUE)
predictors <- lapply(predictors_files, read_tsv_append_column) %>% bind_rows
names(predictors) %<>% fix_names
```

```{r}
qplot(sample_of_312$number_of_theaters)

MOVIE <- "The_King%27s_Speech"
ID1 <- 117
df <- left_join(
    ##sample_of_312 %>% filter(wp_page_title==MOVIE),
    sample_of_312 %>% filter(id==ID1),
    predictors,
    by="id"
    )
```



```{r}
DAYS <- -30

day_subset <- predictors %>% filter(day_movie_time==DAYS)

df <- sample_of_312 %>% select(id, title, first_weekend_revenue_usd,
                               number_of_theaters) %>%
    left_join(., day_subset, by="id") %>%
    select(-day_movie_time)
```

## Model: Theatres only
```{r}
mod <- lm(first_weekend_revenue_usd ~ number_of_theaters, data=df)
mod %>% summary
```
## Model: Except Theatres
```{r}
mod <- lm(first_weekend_revenue_usd ~ views + users + rigor + edits,
          data=df)
mod %>% summary
```

## Model: All 5 predictors
```{r}
mod <- lm(first_weekend_revenue_usd ~ number_of_theaters + views + users + rigor + edits,
          data=df)
mod %>% summary
```

